config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'

  get 'news/index'

  get 'news/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roles
  devise_for :users

   root 'welcomes#index'

   resources :welcomes, only: [:index, :new, :create, :show]

   resources :news, only: [:index, :show]

   resources :schedules, only: [:index]

   get '/robots.:format' => 'welcomes#robots'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/news.rb
class News < ActiveRecord::Base
	dragonfly_accessor :image
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable     
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  	@news = News.all
  end

  def show
  	@new = News.find(params[:id])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
  	@schedules = Schedule.all
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController 
  def index
    @welcomes = Welcome.all
    @welcome = Welcome.new
  end

  def new
    @welcome = Welcome.new
  end

  def create
    @welcome = Welcome.new(welcome_params)
      if @welcome.save
        WelcomeMailer.welcome_email(@welcome).deliver_now  # welcomemailer общий класс, welcome_email - это класс, и переменная
        redirect_to root_path
      else 
        render 'new'
      end
  end

  def show 
    @welcome = Welcome.find(params[:id])
  end

  def robots
    respond_to :text
    expires_in 6.hours, public: true
  end

private
  def welcome_params
    params.require(:welcome).permit(:name, :phone, :departure, :arrival, :date, :count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Пассажирские перевозки Донбасс-Крым. Донецк,Горловка,Макеевка,Севастополь,Симферополь и другие города.</title>
  <meta name="Description" content="Регулярные пассажирские перевозки маршрутом Донбасс - Крым. Ежедневно, в обе стороны. Наш маршрут : Горловка-Енакиево-Донецк-Макеевка-Харцызск-Зугрэз-Шахтерск-Торез-
Краснодар-Севастополь-Ялта-Алушта-Симферополь-Феодосия-Керчь. Продление миграционной карты. Стоимость билета 2.000 рублей">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- GOOGLE ANALYTICS SCRYPT -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-88787410-1', 'auto');
    ga('send', 'pageview');
  </script> 

  <!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter41978524 = new Ya.Metrika({
                    id:41978524,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/41978524" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

  <!--  YANDEX, MAIL SEARCH CODE VERIFICATION-->
  <meta name="yandex-verification" content="7d82e86a0c0fa706" />
  <meta name='wmail-verification' content='2ecfe473b6cf8b63911f1e5ed191671c' />

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= yield %>


    <!--=========== BEGAIN CONTACT FEATURE SECTION ================-->
    <section id="contactFeature">
      <!-- SKILLS COUNTER OVERLAY -->
      <div class="slider_overlay"></div>
      <div class="row">
        <div class="col-lg-12 col-md-12">       
          <div class="container">               
              <div class="contact_feature">
            <!-- BEGAIN CALL US FEATURE -->
            <div class="col-lg-3 col-md-3 col-sm-6">
              <div class="single_contact_feaured wow fadeInUp">
                <i class="fa fa-phone"></i>
                <h4>Позвоните нам</h4>
                <p><a style="color: white" href="tel:+380993558725">+380993558725</a></p>                
              </div>
            </div>
            <!-- BEGAIN CALL US FEATURE -->
            <div class="col-lg-3 col-md-3 col-sm-6">
              <div class="single_contact_feaured wow fadeInUp">
                <i class="fa fa-envelope-o"></i>
                <h4>Viber</h4>
                <p><a style="color: white" href="viber://add?number=+380505519577">+380505519577</a></p>
              </div>
            </div>
            <!-- BEGAIN CALL US FEATURE -->
            <div class="col-lg-3 col-md-3 col-sm-6">
              <div class="single_contact_feaured wow fadeInUp">
                <i class="fa fa-phone"></i>
                <h4>Крым</h4>
                <p><a style="color: white" href="tel:+79787193442">+79787193442</a></p>
              </div>
            </div>
            <!-- BEGAIN CALL US FEATURE -->
            <div class="col-lg-3 col-md-3 col-sm-6">
              <div class="single_contact_feaured wow fadeInUp">
                <i class="fa fa-clock-o"></i>
                <h4>Время работы</h4>
                <p style="color: white">8:00-21:00</p>
              </div>
            </div>
          </div>
          </div>         
        </div>
      </div>
    </section>
    <!--=========== END CONTACT FEATURE SECTION ================-->

     <!--=========== BEGAIN FOOTER ================-->
     <footer id="footer">
       <div class="container">
         <div class="row">
           <div class="col-lg-6 col-md-6 col-sm-6">
             <div class="footer_left">
				<!--=========== Designed By WpFreeware Team ================-->
               <p>Copyright &copy; 2016 <a href="https://vk.com/club131517412">Tandem-Tour</a>. All Rights Reserved</p>
               <p>По вопросам сотрудничества звоните или пишите в Viber на номер: <a href='tel:+380505519577'>+380505519577</a> <br>Почта: <a href='mailto:feolyar@rambler.ru'>fedyar@rambler.ru</a> </p>
			   <!--=========== Designed By WpFreeware Team ================-->
             </div>
           </div>
           <div class="col-lg-6 col-md-6 col-sm-6">
             <div class="footer_right">
               <ul class="social_nav">
                 <li><a href="https://vk.com/club131517412"target="https://vk.com/club131517412"><i class="fa fa-vk"></i></a></li>
               </ul>
             </div>
           </div>
         </div>
       </div>
      </footer>
      <!--=========== END FOOTER ================-->
</body>
</html>

app/views/news/index.html.erb
    <!--=========== BEGAIN BLOG SECTION ================-->
    <section id="blog">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <!-- START BLOG HEADING -->
            <div class="heading">
              <h2 class="wow fadeInLeftBig">Наши новости</h2>
              <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </p>
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <!-- BEGAIN BLOG CONTENT -->
            <div class="blog_content">
            <% @news.each do |news| %>
            <%= render "schedules/index" %>
              <!-- BEGAIN BLOG SLIDER -->
              <div class="blog_slider">
                <!-- BEGAIN SINGLE BLOG -->
                <div class="col-lg-4 col-md-4 col-sm-3">
                  <div class="single_post wow fadeInUp">
                    <div class="blog_img">
                      <%= image_tag news.image.url %>
                    </div>
                    <h3><%= news.title %></h3>
                    <div class="post_commentbox">
                      <span><i class="fa fa-calendar"></i><%= news.created_at %></span>
                    </div>
                    <p><%= news.desc %></p>
                    <a href="#" class="read_more">Read More <i class="fa fa-angle-double-right">  </i></a>
                  </div>
                </div>

                <!-- BEGAIN SINGLE BLOG -->
                <div class="col-lg-4 col-md-4 col-sm-4">
                  <div class="single_post wow fadeInUp">
                    <div class="blog_img">
                      <img src="assets/blog_img1.jpg" alt="img">
                    </div>
                    <h3>Sed ut perspiciatis unde omnis</h3>
                    <div class="post_commentbox">
                      <a href="#"><i class="fa fa-user"></i>Wpfreeware</a>
                      <span><i class="fa fa-calendar"></i>6:49 AM</span>
                      <a href="#"><i class="fa fa-tags"></i>Technology</a>
                    </div>
                    <p>11Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>
                    <a href="#" class="read_more">Read More <i class="fa fa-angle-double-right">  </i></a>
                  </div>
                </div>

                <!-- BEGAIN SINGLE BLOG -->
                <div class="col-lg-4 col-md-4 col-sm-4">
                  <div class="single_post wow fadeInUp">
                    <div class="blog_img">
                      <img src="assets/blog_img1.jpg" alt="img">
                    </div>
                    <h3>Sed ut perspiciatis unde omnis</h3>
                    <div class="post_commentbox">
                      <a href="#"><i class="fa fa-user"></i>Wpfreeware</a>
                      <span><i class="fa fa-calendar"></i>6:49 AM</span>
                      <a href="#"><i class="fa fa-tags"></i>Technology</a>
                    </div>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>
                    <a href="#" class="read_more">Read More <i class="fa fa-angle-double-right">  </i></a>
                  </div>
                </div>                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--=========== END BLOG SECTION ================-->
    <% end %>

app/views/news/show.html.erb
<h1>News#show</h1>
<p>Find me in app/views/news/show.html.erb</p>

app/views/schedules/index.html.erb
<table class="table table-hover">
    <thead>
      <tr>
        <th>Время<br>отправления</th>
        <th>Город</th>
        <th>Место<br> отправления</th>
        <th>Время <br>прибытия</th>
      </tr>
    </thead>
    <tbody>
    <% @schedules.each do |s| %>
      <tr>
        <td><%= s.deptime %></td>
        <td><%= s.city %></td>
        <td><%= s.street %></td>
        <td><%= s.aparttime %></td>
      </tr> 
    <% end %>             
    </tbody>
</table>

app/views/welcomes/new.html.erb
<!--=========== BEGAIN CONTACT SECTION ================-->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <!-- START CONTACT HEADING -->
        <div class="heading">
        <br>
        <br>
          <h2 class="wow fadeInLeftBig">Контакты</h2>
          <p>Оставьте заявку, и мы Вам обязательно перезвоним в скором времени. Либо позвоните на любой из этих номеров:<br>
            <a href="+380993558725">+380993558725</a> 
            <a href="+380713078147">+380713078147</a> 
            <a href="+380505519577">+380505519577 (Viber)</a>
            <a href="+797871934452">+797871934452 (Крым)</a> 
          </p>
        </div>
      </div>
    </div>       
    <div class="row">
      <!-- BEGAIN CONTACT CONTENT -->
      <div class="contact_content">
        <!-- BEGAIN CONTACT FORM -->
        <div class="col-lg-5 col-md-5 col-sm-5">
          <div class="contact_form">

            <!-- FOR CONTACT FORM MESSAGE -->
            <div id="form-messages"></div>
              <%=simple_form_for @welcome, url: welcomes_path do |f| %>
                <%=f.input :name,  :input_html => { :class => 'form-control' }, placeholder: 'Имя', :label => 'ФИО' %> 
                <%=f.input :phone,  :input_html => { :class => 'form-control' }, placeholder: 'Телефон', :label => 'Телефон'  %>
                <%=f.input :departure, placeholder: 'Город отправления', collection: [ "Горловка", "Енакиево", "Донецк","Макеевка", "Харцызск", "Зугрэс","Шахтерск", "Торез","Краснодар", "Севастополь","Ялта", "Алушта", "Симферополь", "Феодосия", "Керчь"], :error => false, label: 'Город отправки
',
              :input_html => {:class => 'form-control'} %>
                <%=f.input :arrival, placeholder: 'Город прибытия', collection: [ "Горловка", "Енакиево", "Донецк","Макеевка", "Харцызск", "Зугрэс","Шахтерск", "Торез","Краснодар", "Севастополь","Ялта", "Алушта", "Симферополь", "Феодосия", "Керчь"], :error => false, label: 'Город прибытия',
              :input_html => {:class => 'form-control'} %>
                <%=f.input :date, as: :date, html5: true,  :input_html => { :class => 'form-control' } %>

                <%=f.input :count, placeholder: 'Количество человек', collection:  1..20 , :error => false, label: 'Количество человек', :input_html => {:class => 'form-control'} %> 
                <%=f.submit 'Отправить', :class => 'submit_btn' %>
              <% end %>
          </div>
        </div>
        <!-- BEGAIN CONTACT MAP -->
        <div class="col-lg-7 col-md-7 col-sm-7">
          <div class="contact_map">
          <!-- BEGAIN GOOGLE MAP -->
               <div id="map_canvas"><iframe width="650" height="404" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJNVb0aBd34EARLG93MCufLPM&key=AIzaSyA9SNMQ7Shi_R4a4MSDvi6qPP46C5u23FI" allowfullscreen></iframe></div>
              </div>
        </div>           
      </div>
    </div>      
  </div>             
</section>
<!--=========== END CONTACT SECTION ================-->

app/views/welcomes/robots.html.erb
<% if Rails.env.production? %>
  User-Agent: *
  Allow: /
  Disallow: /admin
  Sitemap: http://www.tandem-tour.com/sitemap.xml
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

Sitemap: http://www.tandem-tour.com/sitemap.xml.gz